blank_issues_enabled: false
contact_links:
  - name: Document
    url: https://sfajs.com
    about: Find the answer in the document first.
  - name: sfajs/core
    url: https://github.com/sfajs/core
    about: This is a problem of @sfajs/core.
  - name: sfajs/http
    url: https://github.com/sfajs/http
    about: This is a problem of @sfajs/http.
  - name: Questions & Discussions
    url: https://github.com/sfajs/core/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
